baseURL = "https://www.agrohorti.com/"
languageCode = "en-us"
title = "Agrohorti"
disablePathToLower = false

#themesDir = "themes"
theme = "kacang"


# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "agrohorti"

# Agar front-matter pakai format YAML
MetaDataFormat = "yaml"

# Number of blog posts in each pagination page
paginate = 9

[permalinks]

# Configures post URLs
post = "/:slug/"

# Make tags and categories work
[indexes]
    tag = "tags"
    category = "categories"

[params]

    # If false, all of blog post will appear on front page (and in pagination)
    truncate = true

    # Author's name (appears in meta tags and under posts)
    author = "Nurohman Fitriyanto"

    # This text appears in site header under website title
    subtitle = "Growing up your agrobusiness with us"

    # Search engine URL
    searchEngineURL = "https://www.google.com/search"

    # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so it was added to index.html manually
    continueReadingText = "Baca selengkapnya..."

    # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
    googleAnalytics = "UA-XXXXX-X"

  # Switch to true to enable RSS icon link
    rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

    # Website's default description
    defaultDescription = "Official Website Agrohorti, kami menyediakan berbagai keperluan anda seputar pertanian, perkebunan, peternakan, dan perikanan"

    # Populate this with your own search keywords - these will appear in meta tags
    # defaultKeywords = ["Agrohorti" , "Pertanian semarang" , "jual bibit semarang" , "jual bibit cabai tomat terong"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Biodata Author
[author]
    name = "Nurohman Fitriyanto"
    homepage = "https://twitter.com/nurohman_id"
    bio = "Enjoy your time"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"